'use client';
import Link from 'next/link';
import {useState} from 'react';
import QRCode from 'qrcode';
import {PDFDocument} from 'pdf-lib';

const META={
'age-calculator':['Age Calculator','Calculate your exact age.'],
'date-calculator':['Date Calculator','Find date differences and add or subtract days.'],
'currency-converter':['Currency Converter','Convert common currencies.'],
'unit-converter':['Unit Converter','Convert length, weight and temperature.'],
'pdf-tools':['PDF Tools','Merge PDF files in your browser.'],
'word-counter':['Word Counter','Count words, characters and reading time.'],
'password-generator':['Password Generator','Generate a strong random password.'],
'qr-code-generator':['QR Code Generator','Create a downloadable QR code.'],
'image-compressor':['Image Compressor','Compress images locally in your browser.'],
'percentage-calculator':['Percentage Calculator','Calculate percentages instantly.']};
const Field=({label,...p})=><label className="field"><span>{label}</span><input {...p}/></label>;
const Button=({children,onClick,light=false})=><button className="btn" style={light?{background:'#f2f4f7',color:'#344054'}:{}} onClick={onClick}>{children}</button>;
function Age(){const[d,setD]=useState(''),[r,setR]=useState('');return <><Field label="Date of birth" type="date" value={d} onChange={e=>setD(e.target.value)}/><Button onClick={()=>{if(!d)return;const b=new Date(d),n=new Date();let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),x=n.getDate()-b.getDate();if(x<0){m--;x+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}setR(`${y} years, ${m} months, ${x} days`)}}>Calculate</Button>{r&&<div className="result">{r}</div>}</>}
function Dates(){const[a,setA]=useState(''),[b,setB]=useState(''),[n,setN]=useState(30),[r,setR]=useState('');return <><div className="row"><Field label="Date" type="date" value={a} onChange={e=>setA(e.target.value)}/><Field label="Second date" type="date" value={b} onChange={e=>setB(e.target.value)}/></div><Field label="Days to add/subtract" type="number" value={n} onChange={e=>setN(e.target.value)}/><div className="row"><Button onClick={()=>a&&b&&setR(Math.round(Math.abs(new Date(b)-new Date(a))/86400000)+' days')}>Difference</Button><Button light onClick={()=>{if(!a)return;let x=new Date(a);x.setDate(x.getDate()+Number(n));setR(x.toISOString().slice(0,10))}}>Add</Button><Button light onClick={()=>{if(!a)return;let x=new Date(a);x.setDate(x.getDate()-Number(n));setR(x.toISOString().slice(0,10))}}>Subtract</Button></div>{r&&<div className="result">{r}</div>}</>}
function Currency(){const[a,setA]=useState(1),[f,setF]=useState('USD'),[t,setT]=useState('BDT'),[r,setR]=useState(''),[busy,setBusy]=useState(false);const cs=['USD','BDT','EUR','GBP','INR','CAD','AUD','JPY'];return <><div className="row"><Field label="Amount" type="number" value={a} onChange={e=>setA(e.target.value)}/><label className="field"><span>From</span><select value={f} onChange={e=>setF(e.target.value)}>{cs.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>To</span><select value={t} onChange={e=>setT(e.target.value)}>{cs.map(x=><option key={x}>{x}</option>)}</select></label></div><Button onClick={async()=>{setBusy(true);try{const res=await fetch(`https://open.er-api.com/v6/latest/${f}`);const j=await res.json();if(!j.rates?.[t])throw Error();setR((Number(a)*j.rates[t]).toFixed(2)+' '+t)}catch{setR('Rate service unavailable. Please try again.')}finally{setBusy(false)}}}>{busy?'Loading…':'Convert'}</Button>{r&&<div className="result">{r}</div>}</>}
function Unit(){const[type,setType]=useState('length'),[v,setV]=useState(1),[f,setF]=useState('meter'),[t,setT]=useState('kilometer'),[r,setR]=useState('');const units={length:{meter:1,kilometer:1000,mile:1609.344,foot:.3048},weight:{gram:1,kilogram:1000,pound:453.59237,ounce:28.3495},temperature:{celsius:0,fahrenheit:1,kelvin:2}};const keys=Object.keys(units[type]);function cat(x){setType(x);const k=Object.keys(units[x]);setF(k[0]);setT(k[1])}function calc(){if(type==='temperature'){const c=f==='celsius'?+v:f==='fahrenheit'?(+v-32)*5/9:+v-273.15;setR((t==='celsius'?c:t==='fahrenheit'?c*9/5+32:c+273.15).toFixed(4));}else setR((+v*units[type][f]/units[type][t]).toFixed(6))}return <><label className="field"><span>Category</span><select value={type} onChange={e=>cat(e.target.value)}><option>length</option><option>weight</option><option>temperature</option></select></label><div className="row"><Field label="Value" type="number" value={v} onChange={e=>setV(e.target.value)}/><label className="field"><span>From</span><select value={f} onChange={e=>setF(e.target.value)}>{keys.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>To</span><select value={t} onChange={e=>setT(e.target.value)}>{keys.map(x=><option key={x}>{x}</option>)}</select></label></div><Button onClick={calc}>Convert</Button>{r&&<div className="result">{r} {t}</div>}</>}
function Words(){const[t,setT]=useState('');const w=t.trim()?t.trim().split(/\s+/).length:0,c=t.length,s=(t.match(/[.!?]+(?=\s|$)/g)||[]).length;return <><textarea rows="12" placeholder="Type or paste text…" value={t} onChange={e=>setT(e.target.value)}/><div className="stats">{[[w,'Words'],[c,'Characters'],[s,'Sentences'],[Math.ceil(w/200),'Min read']].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div></>}
function Password(){const[l,setL]=useState(16),[p,setP]=useState('');function gen(){const chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*_-+=';const a=new Uint32Array(Number(l));crypto.getRandomValues(a);setP(Array.from(a,n=>chars[n%chars.length]).join(''))}return <><Field label="Password length" type="number" min="6" max="64" value={l} onChange={e=>setL(Math.max(6,Math.min(64,e.target.value)))}/><Button onClick={gen}>Generate</Button>{p&&<><div className="password">{p}</div><Button light onClick={()=>navigator.clipboard?.writeText(p)}>Copy</Button></>}</>}
function QR(){const[t,setT]=useState('https://quicktoolbox.example'),[s,setS]=useState('');return <><Field label="Text or URL" value={t} onChange={e=>setT(e.target.value)}/><Button onClick={async()=>setS(await QRCode.toDataURL(t,{width:700,margin:2}))}>Generate QR</Button>{s&&<><div className="qr"><img src={s} alt="Generated QR code"/></div><a className="btn" href={s} download="quicktoolbox-qr.png">Download PNG</a></>}</>}
function ImageTool(){const[o,setO]=useState(''),[info,setI]=useState('');return <><label className="upload">Choose image<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),scale=Math.min(1,1800/im.width);c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);const d=c.toDataURL('image/jpeg',.72);setO(d);setI(`${Math.round(f.size/1024)} KB → about ${Math.round(d.length*.75/1024)} KB`)};im.src=URL.createObjectURL(f)}}/></label>{o&&<><p className="muted">{info}</p><a className="btn" href={o} download="compressed.jpg">Download compressed image</a></>}</>}
function Percent(){const[a,setA]=useState(20),[b,setB]=useState(200),[r,setR]=useState('');return <><div className="row"><Field label="Percentage" type="number" value={a} onChange={e=>setA(e.target.value)}/><Field label="Number" type="number" value={b} onChange={e=>setB(e.target.value)}/></div><Button onClick={()=>setR((Number(a)/100*Number(b)).toFixed(2))}>Calculate</Button>{r&&<div className="result">{r}</div>}</>}
function PDF(){const[fs,setFs]=useState([]),[r,setR]=useState('');async function merge(){try{if(!fs.length)return;const out=await PDFDocument.create();for(const f of fs){const doc=await PDFDocument.load(await f.arrayBuffer());const pages=await out.copyPages(doc,doc.getPageIndices());pages.forEach(p=>out.addPage(p))}const blob=new Blob([await out.save()],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='quicktoolbox-merged.pdf';a.click();URL.revokeObjectURL(url);setR('Merged PDF downloaded.')}catch{setR('Could not read one of the PDF files.')}}return <><label className="upload">Choose PDF files<input type="file" accept="application/pdf" multiple onChange={e=>setFs(Array.from(e.target.files||[]))}/></label><Button onClick={merge}>Merge PDFs</Button>{r&&<p className="success">{r}</p>}</>}
function Tool({slug}){return {'age-calculator':<Age/>,'date-calculator':<Dates/>,'currency-converter':<Currency/>,'unit-converter':<Unit/>,'pdf-tools':<PDF/>,'word-counter':<Words/>,'password-generator':<Password/>,'qr-code-generator':<QR/>,'image-compressor':<ImageTool/>,'percentage-calculator':<Percent/>}[slug]||<p>Tool not found.</p>}

export default function ToolClient({slug}){const m=META[slug]||['Tool not found',''];return <><header><Link className="brand" href="/"><b>Q</b> QuickToolBox</Link><Link href="/">← All tools</Link></header><main className="tool"><small>FREE ONLINE TOOL</small><h1>{m[0]}</h1><p>{m[1]}</p><div className="box"><Tool slug={slug}/></div></main><footer>© 2026 QuickToolBox</footer></>}
