'use client';
import {useMemo,useState} from 'react';
const colors=['navy','blue','indigo','purple','teal','green','emerald','orange','red','slate'];
const layouts=['classic','modern','minimal','executive','sidebar','compact','elegant','creative','academic','corporate','timeline','bold'];
const names=['Classic','Modern','Minimal','Executive','Sidebar','Compact','Elegant','Creative','Academic','Corporate','Timeline','Bold'];
const templates=layouts.flatMap((layout,i)=>colors.map((color,j)=>({id:i*10+j+1,name:`${names[i]} ${j+1}`,layout,color})));
const defaults={name:'YOUR NAME',role:'Professional Title',email:'you@example.com',phone:'+880 1XXXXXXXXX',location:'Rangpur, Bangladesh',summary:'Motivated professional with strong communication, technical and problem-solving skills. Ready to contribute to a growth-focused organization.',skills:'Communication • Microsoft Office • Teamwork • Problem Solving • Leadership',experience:'Job Title — Company Name — 2024–Present\n• Managed daily responsibilities and improved team workflow.\n• Worked with clients and colleagues to deliver quality results.',education:'Degree / Diploma — Institute Name — 2024\nCGPA / Result: 3.50 / 4.00',certificates:'Professional Certificate — Issuing Organization — 2024',languages:'Bangla • English'};
function Field({label,name,form,setForm,area}){return <label className='field'><span>{label}</span>{area?<textarea rows={4} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>}
function Preview({t,f}){return <article className={`cv-paper cv-${t.layout} cv-${t.color}`}><div className='cv-top'><h1>{f.name}</h1><h2>{f.role}</h2><p>{f.email} • {f.phone} • {f.location}</p></div><div className='cv-body'><aside><Section title='CONTACT'><p>{f.email}</p><p>{f.phone}</p><p>{f.location}</p></Section><Section title='SKILLS'><p>{f.skills}</p></Section><Section title='LANGUAGES'><p>{f.languages}</p></Section></aside><div className='cv-main'><Section title='PROFILE'><p className='pre'>{f.summary}</p></Section><Section title='EXPERIENCE'><p className='pre'>{f.experience}</p></Section><Section title='EDUCATION'><p className='pre'>{f.education}</p></Section><Section title='CERTIFICATES'><p className='pre'>{f.certificates}</p></Section></div></div></article>}
function Section({title,children}){return <section className='cv-section'><h3>{title}</h3>{children}</section>}
export default function CVMaker(){const [form,setForm]=useState(defaults);const [selected,setSelected]=useState(1);const [query,setQuery]=useState('');const t=templates[selected-1];const filtered=useMemo(()=>templates.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())||x.layout.includes(query.toLowerCase())||x.color.includes(query.toLowerCase())),[query]);return <><header><a className='brand' href='/'><b>Q</b>QuickToolBox</a><a href='/'>← All tools</a></header><main className='cv-page'><div className='cv-heading'><small>CV MAKER</small><h1>120 professional CV templates</h1><p>Enter your details, choose a design, then use your browser's Print → Save as PDF.</p></div><div className='cv-layout'><div className='cv-editor'><div className='box'><h2>Your information</h2><div className='row'><Field label='Full name' name='name' form={form} setForm={setForm}/><Field label='Professional title' name='role' form={form} setForm={setForm}/></div><div className='row'><Field label='Email' name='email' form={form} setForm={setForm}/><Field label='Phone' name='phone' form={form} setForm={setForm}/></div><Field label='Location' name='location' form={form} setForm={setForm}/><Field label='Profile summary' name='summary' form={form} setForm={setForm} area/><Field label='Skills' name='skills' form={form} setForm={setForm} area/><Field label='Experience' name='experience' form={form} setForm={setForm} area/><Field label='Education' name='education' form={form} setForm={setForm} area/><Field label='Certificates' name='certificates' form={form} setForm={setForm} area/><Field label='Languages' name='languages' form={form} setForm={setForm}/><button className='btn' onClick={()=>window.print()}>Print / Save PDF</button></div><div className='box'><h2>Choose a template</h2><input className='template-search' placeholder='Search 120 templates…' value={query} onChange={e=>setQuery(e.target.value)}/><div className='template-grid'>{filtered.map(x=><button className={`template-card ${selected===x.id?'active':''}`} key={x.id} onClick={()=>setSelected(x.id)}><div className={`mini cv-${x.layout} cv-${x.color}`}><b>{form.name||'YOUR NAME'}</b><small>{x.name}</small><i></i><i></i><i></i></div><strong>{x.name}</strong><span>Template #{x.id}</span></button>)}</div></div></div><div className='cv-preview'><div className='preview-bar'><b>Live Preview — {t.name}</b><span>#{t.id} / 120</span></div><Preview t={t} f={form}/></div></div></main><footer>© 2026 QuickToolBox • Original CV template collection</footer></>}
